labels:
  Deploy%20to%20Staging:
    environment: staging
  deploy-to-test:
    environment: test
    description: A test environment based on Docker
    transient_environment: true
    auto_merge: false
    required_contexts:
      - continuous-integration/travis-ci/push
    payload:
      port: 8080
      https: true
  deploy-to-hugo:
    environment: hugo
    description: A test environment based on Docker
    transient_environment: true
    auto_merge: false
    payload:
      port: 8080
      https: true      
